cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - node_modules
branches:
  only:
  - beta
notifications:
  email:
    on_success: never
    on_failure: always
 
 
matrix:
  include:
    - language: android
      ..........
      ...........
 
    - language: objective-c
      os: osx
      osx_image: xcode9.0
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
        - gem install fastlane --no-rdoc --no-ri --no-document --quiet
        - openssl aes-256-cbc -K $encrypted_***_key -iv $encrypted_***_iv -in .deploy_key.enc -out ~/.ssh/deploy_key -d
        - echo -e "Host github.com\n\tHostName github.com\n\tUser git\n\tIdentityFile ~/.ssh/deploy_key\n" >> ~/.ssh/config
        - ssh-keyscan github.com >> ~/.ssh/known_hosts
        - chmod 600 ~/.ssh/deploy_key
      install:
        - travis_retry yarn
      script:
        - cd ios
        - fastlane beta --capture_output